# Generated by Django 4.1.7 on 2023-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=10000)),
            ],
        ),
    ]
